Repository yumemi-inc/accessibility-guidelines, pull requests merged in 2025-04, with the labels that each got.

#48 ガイドラインのトンマナ作成
  astro.config.mjs
  package.json
  pnpm-lock.yaml
  src/assets/yumemi_logo_dark.svg
  src/assets/yumemi_logo_light.svg
  src/components/footer.astro
  src/styles/custom.css
Labels: enhancement, Review観点2: 動作確認

#50 トップページにOGPの設定を追加
  astro.config.mjs
  public/og.png
  src/content/docs/index.mdx
Labels: Review観点2: 動作確認

#51 chore: textlint を mdx にもかけるように
  .textlintrc
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
Labels: Review観点2: 動作確認

#49 docs: AIフレンドリーなドキュメントにアップデート
  .cursor/rules/guideline-rules.mdc
  .textlintrc
  src/content/docs/about/introduction.md
  src/content/docs/about/usage.md
  src/content/docs/guidelines/1.1.1.mdx
  src/content/docs/guidelines/1.4.1.mdx
  src/content/docs/guidelines/1.4.3.mdx
  src/content/docs/guidelines/2.3.1.mdx
  src/content/docs/guidelines/2.4.6.mdx
  src/content/docs/guidelines/_template.mdx
Labels: documentation, Review観点3: 仕様

#63 style: トンマナとレイアウトの調整
  src/styles/custom.css
Labels: enhancement, Review観点1: 軽く目を通す

#67 ページタイトルの修正（β版の表記も追記）
  astro.config.mjs
  src/components/site-title.astro
Labels: enhancement, Review観点2: 動作確認
